### ISSUE TITLE
Error in Burdenko GBM Progression bidsmap

### ISSUE THREAD

**Issue by RaphaelMaser** [LuxImagingAI/URT#15]

**Comment by RaphaelMaser** [comment]
`09/12/2024 04:47:14 DEBUG: Traceback (most recent call last):
09/12/2024 04:47:14 DEBUG: File "/condaforge/envs/URT/bin/bidsmapper", line 8, in <module>
09/12/2024 04:47:14 DEBUG: sys.exit(main())
09/12/2024 04:47:14 DEBUG: ^^^^^^
09/12/2024 04:47:14 DEBUG: File "/condaforge/envs/URT/lib/python3.11/site-packages/bidscoin/bidsmapper.py", line 251, in main
09/12/2024 04:47:14 DEBUG: bidsmapper(rawfolder    = args.sourcefolder,
09/12/2024 04:47:14 DEBUG: File "/condaforge/envs/URT/lib/python3.11/site-packages/bidscoin/bidsmapper.py", line 141, in bidsmapper
09/12/2024 04:47:14 DEBUG: module.bidsmapper_plugin(sesfolder, bidsmap_new, bidsmap_old, template, store)
09/12/2024 04:47:14 DEBUG: File "/condaforge/envs/URT/lib/python3.11/site-packages/bidscoin/plugins/dcm2niix2bids.py", line 171, in bidsmapper_plugin
09/12/2024 04:47:14 DEBUG: if not datasource.datatype=='' and 'part' in run['bids'] and not run['bids']['part'][-1] and run['attributes'].get('ImageType'):    # part[-1]==0 -> part is not specified
09/12/2024 04:47:14 DEBUG: ~~~~~~~~~~~~~~~~~~~^^^^
09/12/2024 04:47:14 DEBUG: TypeError: 'NoneType' object is not subscriptable
09/12/2024 04:47:14 ERROR: An error occurred during download of collections Burdenko-GBM-Progression
Traceback (most recent call last):
  File "/URT/URT.py", line 414, in main
    downloader.run()
  File "/URT/URT.py", line 119, in run
    self.convert_to_bids()
  File "/URT/URT.py", line 251, in convert_to_bids
    run_subprocess(command, logger=self.logger)
  File "/URT/utils/utils.py", line 45, in run_subprocess
    raise Exception(f"Command '{command}' returned non-zero exit status {exitcode}")
Exception: Command 'bidsmapper -f -a -n "Burdenko-GBM-" -m "*" "/URT/temp/Burdenko-GBM-Progression" "/URT/temp/Burdenko-GBM-Progression_BIDS" -t "/URT/datasets/bidsmaps/Burdenko-GBM-Progression.yaml" -p "dcm2niix2bids"' returned non-zero exit status 1
`
